---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  dynamic_conf.yml: |
    http:
      routers:
        api:
          rule: Host(`traefik.localhost`)
          service: api@internal
          entrypoints:
            - web
            - websecure
          middlewares:
            - auth
      middlewares:
        auth:
          basicAuth:
            users:
              - "traefik:$apr1$vg9o1njw$PC83XopuGBGOCof5FQ6iW/" #traefik/kubecon
