---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
  namespace: traefik
spec:
  ports:
    - name: web
      port: 80
    - name: websecure
      port: 443
    - name: mongo
      port: 27017
  selector:
    app: traefik-ingress-controller
  type: LoadBalancer
