= Containous Slides

== How-to Work with this?

=== Requirements

* You need:
** Docker CE 18.09+ (with local bind-mount capability -
Docker4Mac, Docker4Windows or a local Linux Docker install)
** docker-compose in your PATH
(automatically installed with Docker4Mac and Docker4Windows)
** GNU Make in your PATH

== Generate the slides

* If you want to generate the slide-deck in "one shot":
** Clone the repository
** Run the following `make` command:
+
[source,bash]
----
make build
----

** Open the resulting file `./dist/index.html`

=== Working on the slides with Live-reloading

* If you want to build and serve the slides locally,
with a live-reloading capability
(e.g. change a `*.adoc`, regenerate the HTML and reload the web-browser)
to get a WYSIWYG experience:

** Clone the repository
** Run the following `make` command:
+
[source,bash]
----
make serve
----

** Open the URL link:http://localhost:8000
** Edit one of the `*.adoc` file, save it, and see the page reload
*** it is valid for images and styles also

=== Run checks on the generated HTML

You can validate the HTTP links and the HTML's w3c compliance
of the generated slide deck.

If you already generated the file `./dist/index.html`,
then run the following `make` command:
+
[source,bash]
----
make verify
----

Otherwise, you can run the `all` command ,as the CI process is doing:
+
[source,bash]
----
make all
----

=== Maintenance tasks inside the container

If you want to get a shell inside the "build and serve" container,
run the following `make` command:
+
[source,bash]
----
make shell
----

==== Example: updating the package.json (and lock) depencies

[source,bash]
----
make shell
/app # ncu -u
...
----
