version: '2.4'

services:
  edge:
    image: traefik:v1.7.11
    command:
      - "--docker" # Tells Traefik to listen to docker
      - "--api"
    ports:
      - "80:80"
    volumes:
      # To communicate with the Docker Engine
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik.toml:/traefik.toml
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:dashboard.docker.localhost"
  web:
    build:
      context: ./hugo/
      dockerfile: Dockerfile
    environment:
      - HUGO_ENV=docker
    labels:
      - "traefik.frontend.rule=Host:${EXTERNAL_HOST}"
  jenkins:
    image: jenkins/jenkins:2.164.2-alpine
    expose:
      - 8080
      - 50000
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${EXTERNAL_HOST};PathPrefix:/jenkins"
  gitserver:
    image: gitea/gitea:latest
    expose:
      - "3000"
      - "22"
    environment:
      - ROOT_URL=/gitserver
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:${EXTERNAL_HOST};PathPrefixStrip:/gitserver"
  ttyd:
    image: tsl0922/ttyd:1.4.2-alpine
    labels:
      - "traefik.frontend.rule=Host:${EXTERNAL_HOST};PathPrefixStrip:/ttyd"
  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:${WHOAMI_EXTERNAL_HOST}"
      - "traefik.frontend.headers.customRequestHeaders=X-Traefik-Header:Powpow"
