apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
spec:
  entryPoints:
    - http
    #- https
  routes:
  - match: Host(`meetup.manuelzapf.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  #tls:
   #certResolver: defaults