[{invert}]
= Lab 2

* **{agenda-acme}**
* {agenda-rp}
* {agenda-web}
* {agenda-ci}
* {agenda-scm}
* {agenda-ws}

== Goal

* We want to use our generated Let's Encrypt certificates.
** We do not want to exceed link:https://letsencrypt.org/docs/rate-limits/["the ACME Rate Limits.",window=_blank].

== Retrieve Certificates from Docker

* Step 1: From the "Legacy" (Docker) VM:

[source,bash,subs="attributes"]
----
# Get Traefik Container ID
TRAEFIK_CONTAINER_ID="$(docker ps | grep traefik | grep edge | awk '{print $1}')"

# Generate a file "certs.b64" in the user home
docker run --rm --volumes-from="${TRAEFIK_CONTAINER_ID}" -t \
    alpine cat /acme/acme.json | base64 > ~/certs.b64
----

* Step 2: From the "bastion", copy the certificates to the new VM

[source,bash,subs="attributes"]
----
ssh {docker_vm_ip} cat certs.b64 | ssh {kube_vm_ip} "cat > certs.b64"
----

== Import Certificates into Kubernetes

**Idea:**

* On the "Kube" VM, we'll create a pod with a PVC ("Persistent Volume Claim").
* Then, using this pod, we'll populate the persistent volume with the `acme.json` data.
* After that, we'll be able to install the Traefik Ingress configured to use this PVC.

== Prepare PVC in Kubernetes

* Step 1: Create the PVC ("Persistent Volume Claim") manifest file `acme-pvc.yml`:
+
[source,yaml,indent=0,subs="attributes+"]
----
include::../../demo/lab-docker-k8s/02-k8s-traefik/acme/pvc.yml[tag=pvc]
----

* Step 2: create namespace and PVC:
+
[source,bash,subs="attributes"]
----
kubectl create namespace devoxx
kubectl apply -f acme-pvc.yml
----

== Prepare the "acme-loader" Deployment

* Step 1: Create the manifest file `acme-deploy.yml`:
+
[source,yaml,indent=0,subs="attributes+"]
----
include::../../demo/lab-docker-k8s/02-k8s-traefik/acme/pvc.yml[tag=deploy]
----

* Step 2: create the deployment:
+
[source,bash,subs="attributes"]
----
kubectl apply -f acme-pod.yml
----

== Load ACME data in Kubernetes

* Step 1: Wait for the pod and pvc to be created:
+
[source,bash,subs="attributes"]
----
# Expecting the pod "acme-loader" to be in state "Running"
watch kubectl get pod,pv,pvc --namespace=devoxx
# Then hit CTRL-C
----

* Step 2: Decode ACME data and copy it:
+
[source,bash,subs="attributes"]
----
base64 --decode certs.b64 > ~/acme.json
chmod 0600 ~/acme.json
kubectl --namespace=devoxx cp ~/acme.json acme-loader:/acme/
kubectl exec --namespace=devoxx acme-loader -- ls -l /acme
# the file "acme.json" MUST be in 600 (-rw-------)
----

* Step 3: Remove the "acme-loader" deployment:
+
[source,bash,subs="attributes"]
----
kubectl delete -f acme-pod.yml
----

== That's all

Ready to go to the next step!
