apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
spec:
  ports:
    - name: web
      port: 80
    - name: admin
      port: 8080
    - name: websecure
      port: 443
  selector:
    app: traefik-ingress-controller
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami