= Lab 2

== Install Helm

[source,bash]
----
#!/usr/bin/env bash

echo "install helm"

# installs helm with bash commands for easier command line integration
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

# add a service account within a namespace to segregate tiller
kubectl --namespace kube-system create sa tiller

# create a cluster role binding for tiller
kubectl create clusterrolebinding tiller \
    --clusterrole cluster-admin \
    --serviceaccount=kube-system:tiller

echo "initialize helm"

# initialized helm within the tiller service account
helm init --service-account tiller

# updates the repos for Helm repo integration
helm repo update
echo "verify helm"

# verify that helm is installed in the cluster
kubectl get deploy,svc tiller-deploy -n kube-system
---

== Install Traefik with default configuration
+
[source,bash]
---
helm install stable/traefik --name traefik-devoxx --namespace kube-system
helm ls
helm delete --purge traefik-devoxx
---

== Install Traefik with custom configuration
+
[source,bash]
---
helm install stable/traefik --name traefik-devoxx --namespace devoxx -f ./values.yml
helm ls
helm delete --purge traefik-devoxx
---

== Notes
+
- `helm upgrade` does not work as expected (pod never stoppped)
- ACME on dashboard: will not work because domain is not set on LoadBalancer, adding timeout works for tls? => enable ingress after manually
- helm by default set `tls-sni-challenge` instead of ` tls-alpn-challenge`