# ---
# apiVersion: storage.k8s.io/v1beta1
# kind: StorageClass
# metadata:
#   name: gp2
#   annotations:
#     storageclass.beta.kubernetes.io/is-default-class: "true"
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-storage
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
